let UnitTest = require("unit-test")
io.exit(UnitTest("Charly").begin(func(describe) {
  describe("Including external files",            require("./external-files.ch"))
  describe("Variables",                           require("./variables.ch"))
  describe("Arithmetic operations",               require("./arithmetic.ch"))
  describe("Comparisons",                         require("./comparisons.ch"))
  describe("Arrays",                              require("./arrays.ch"))
  describe("Numerics",                            require("./numerics.ch"))
  describe("Strings",                             require("./strings.ch"))
  describe("Functions",                           require("./functions.ch"))
  describe("Classes",                             require("./classes.ch"))
  describe("Objects",                             require("./objects.ch"))
  describe("While loops",                         require("./while-loops.ch"))
  describe("Misc. standard library functions",    require("./misc-std.ch"))
  describe("CLI",                                 require("./cli.ch"))
  describe("Math",                                require("./math.ch"))
  describe("try & catch",                         require("./exceptions.ch"))
  describe("Magic constants",                     require("./magic-constants.ch"))
  describe("References",                          require("./references.ch"))
  describe("Primitives",                          require("./primitives.ch"))
}))
