require "spec"
require "../src/charly/interpreter/fascade.cr"
require "../src/charly/interpreter/types.cr"
require "../src/charly/interpreter/stack/stack.cr"
require "../src/charly/interpreter/interpreter.cr"
